version: '3.7'
services:
        mysql:
            image: mysql:8.0
            ports:
                - 3306:3306
                - 33060:33060
            environment:
                - MYSQL_ROOT_PASSWORD=pass
                - MYSQL_DATABASE=social
                - MYSQL_USER=app
                - MYSQL_PASSWORD=pass